version: '3'


services:
  prometheus_shtc3:
    build:
      context: ./shtc3_prometheus/
    restart: always
    devices:  
      - "/dev/i2c-1:/dev/i2c-1" 
    ports:
      - 8188:8188
    environment:
      - TZ=America/Chicago
      - room=${room}
